repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: detect-private-key

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(js|ts|jsx|tsx|css|json|md|html|yml|yaml|svelte)$
        args: ['--config', './.prettierrc', '--write']

  - repo: local
    hooks:
      - id: eslint
        name: ESLint
        entry: pnpm lint
        language: system
        pass_filenames: false
        files: \.(js|ts|jsx|tsx|svelte)$

      # - repo: local
      #   hooks:
      #     - id: check-types
      #       name: TypeScript type check
      #       entry: pnpm check
      #       language: system
      #       pass_filenames: false
      #       files: \.(ts|tsx|svelte)$

      - id: build
        name: Build check
        entry: pnpm build
        language: system
        pass_filenames: false
        files: \.(js|ts|jsx|tsx|svelte|css)$
        stages: [pre-push]
